name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'

jobs:
  testsuite:
    name: suite
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: "Install system dependencies"
      run: |
        sudo apt update -y
        sudo apt install -y openssl-dev asio-dev

    - name: "Install python environment"
      run: |
        pip --user install black flake8 mypy pytest
        pip --user install -e .

    - name: "Run black"
      run: |
        black --check src/vroom

    - name: "Run flake8"
      run: |
        flake8 src/vroom

    - name: "Run mypy"
      run: |
        mypy src/vroom

    - name: "Run pytest"
      run: |
        pytest --doctest-modules test src/vroom

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

  wheel_check:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.image }}
    strategy:
      fail-fast: true
      matrix:
        include:
          # - image: ubuntu-latest
          #   platform: linux
          - image: macos-latest
            platform: macos
          - image: windows-latest
            platform: windows

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache Conan
      id: cache-conan
      uses: actions/cache@v2
      if: matrix.platform == 'windows'
      with:
        path: |
          conan_build
          conan_data
        key: conan-${{ matrix.image }}-${{ hashFiles('conanfile.txt') }}

    - name: Configure Python
      uses: actions/setup-python@v2
      if: matrix.platform == 'windows' && steps.cache-conan.outputs.cache-hit != 'true'
      with:
        python-version: '3.x'

    - name: Install Conan
      if: matrix.platform == 'windows' && steps.cache-conan.outputs.cache-hit != 'true'
      run: |
        pip install pip --upgrade
        pip install conan
        conan profile new default --detect
        conan profile update "settings.compiler=Visual Studio" default
        conan profile update "settings.compiler.version=16" default
        conan config set "storage.path=$env:GITHUB_WORKSPACE/conan_data"
        conan install --build=openssl --install-folder conan_build .

    - uses: pypa/cibuildwheel@v2.3.1
      env:
        MACOSX_DEPLOYMENT_TARGET: 10.14
        CIBW_BUILD: '*cp37*'

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash
